language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: O8gNsJ4y45AX7JlakRJfQoUiiV6mU3EJ7lQD9RNOZ7FKL48eliFHVgLPDI5rmDqeUoEVvNL5QEhEarI0dZsZh2NciFMS1kGvYGxCv4eUDhq828fqrUCxzPjcLGv/DwNrVhhUfiLJziDPqlyrdNMaHGmn1Ix7uwC7mAoOxLhThHmUkmO+K3ci8ea4DXT3VGRslqUrX0D/IJlBD1BH4jFT5YXIbqLG58nl3Su4NzfBaXFyAmcBiNNJWhKOF0e1YrHL0DvJPpjx0cYy1HVBWSgVw2bgaUUg0vUXFFQsboZtTueDF2qAU3f+I2tZSeNKKfvktJ+SzTknPdsogchMkSlY4FB4nyhYMPCkhkF9lTjUbi0gdlEC31oMTaCesZh28AGujKQoX4rilRFxbTnasEiYHbv4CtCK/ae211Fmb9E+9xHCeqxFMvE7xusJrYkKfHA2x2SjksDm0Nc4HxLknBSGm6zdvW0a6P0sV4Ie5HY6TbXeFlw26z7QMGJRtzcBQrDv8I9z5RaUkP4ACc4V9Pw2xJS7BXyJDfvDxF8l92F7BrxjSQnodZ4Ye3oBHhVbNcXLrDEhyfTHjnWfQMg7kIN4UAl6rVN9reUSquMxat8tVRKjf/Oe3Q1z25vXrhkkIW9w1zgP6/lF5X7lDcdXfYUAr3EH+G8D+JfZxIxUjGaICz8=
  on:
    repo: FreeAllMedia/jsonapi-formatter
    branch: master
